server:
  port: 8999

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: gfc-services
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: 123
#    resource:
#       userInfoUri: http://localhost:9999/uaa/user

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8999/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user